container:
    # REQUIRED
    # Specify an FQIN or Docker Hub image.
    image: fedora:25

# OPTIONAL
# List of packages to install during provisioning. If
# running on an Atomic Host variant, packages will be
# layered.
packages:
    - autoconf
    - automake
    - make
    - gcc
    - git
    - pkgconfig(json-glib-1.0)
    - libseccomp-devel
    - libxslt
    - bubblewrap
    - docbook-style-xsl
    - pkgconfig(gio-unix-2.0)

build: true

tests:
    - make check

branches:
  - master
  - auto
  - try

# OPTIONAL
# Time to allow before aborting tests. Must satisfy regex
# '[0-9]+[smh]'. If omitted, defaults to '2h', which is the
# maximum.
timeout: 30m

# OPTIONAL
# List of files/directories to upload to Amazon S3.
artifacts:
    - test-suite.log
